[package]
name = "orbweaver"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core biotechnology libraries
bqtools = "0.1.0"  # For VBQ format handling
bio = "1.3.1"      # Rust bioinformatics library

# Data structures and algorithms
petgraph = "0.6.3" # Graph data structures
fm-index = "0.1.0" # FM-Index for efficient substring queries

# Parallelization
rayon = "1.7.0"    # Data parallelism library

# Database integration
neo4rs = "0.6.2"   # Neo4j Rust driver

# Utility libraries
anyhow = "1.0.72"  # Error handling
clap = { version = "4.3.19", features = ["derive"] } # Command line argument parsing
serde = { version = "1.0.174", features = ["derive"] } # Serialization/deserialization
serde_json = "1.0.103" # JSON support
tempfile = "3.6.0" # Temporary file handling

# Async runtime
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "time"] }

# Logging
log = "0.4.19"
env_logger = "0.10.0"
